server:
  http_listen_port: 9090
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'java-logs' # Name of the job
    static_configs:
      - targets:
          - loki
        labels:
          job: java-app # Custom label for the job
          container_name: java-app # Another custom label
          log_level: info
          __path__: /var/log/java-app/*.log  # Path to Java app logs
