global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'java-app'
    static_configs:
      - targets: ['java-app:9091']  # Adjust this port if your metrics are exposed elsewhere
